@stickyNote=#FEFF9C
@background=#082f49
@accent=#B0C4DE
@button=#B0C4DE

TitlePane.unifiedBackground=false
TitlePane.background=darken(@accent,45%)



Component.focusWidth=1
Component.arc=10
Button.arc=10
Button.font=bold
Button.margin=10,20,10,20
TextComponent.arc=10
TextField.margin=4,6,4,6
PasswordField.margin=4,6,4,6

TextField.background=lighten(@background,10%)
PasswordField.background=lighten(@background,10%)
TextArea.background=lighten(@background,10%)
